Neo4j APIの記事
SystemEngineeringTeam/sysken-book-2023 pull request #31
Opened 2023-04-27 03:51 UTC by karasuneo

## 概要

## チェックリスト

### Texについての確認リスト
- [ ] ビルドが通るか
- [ ] 余分な空ページはないか？
- [ ] セクションの番号は合っているか？

### 内容についての確認リスト
- [ ] 内容に誤字脱字はないか？
- [ ] 図と表は正しくラベル付けされているか？
- [ ] 引用は正しく行えているか？
- [ ] あいまいな文章やねじれている文章になっていないか？
- [ ] 段落内・段落同士のつながりは適切か？

## コメント

2023-04-28 15:47 UTC, hihumikan commented
@karasuneo 
一度確認しておきたいのですが、そちらの環境ではbuild出来ましたでしょうか？
当方の環境だとbuild時にエラーを吐いてpdfが生成できないのです...

2023-04-28 15:56 UTC, hihumikan reviewed
@karasuneo
一度確認しておきたいのですが、そちらの環境ではbuild出来ましたでしょうか？
当方の環境だとbuild時にエラーを吐いてpdfが生成できないのです...

2023-05-07 04:51 UTC, hihumikan commented
Conflictも直してもらえると嬉しいです！

2023-05-07 13:49 UTC, karasuneo commented
直しました！

2023-05-07 14:25 UTC, hihumikan reviewed
@karasuneo 
4.2と4.4で使う画像がかなり小さいので、修正お願いします！　

2023-05-07 14:25 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +\includegraphics[width=4cm]{./image/03-Tech/chap3/sample_node.png}
確認ですが、ここのサイズは4cm四方で良かったですか？

2023-05-07 14:25 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +\subsection{Docker環境の設定}
ファイル名が抜けている箇所があるので、どちらかに表記統一した方がいい気がします！
```suggestion
compose.yaml
\subsection{Docker環境の設定}
```

2023-05-07 14:25 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +\includegraphics[width=4cm]{./image/03-Tech/chap3/neo4j_result.png}
こちらも4ch四方で良かったですか？

2023-05-07 14:25 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +\begin{tcolorbox}[breakable]
お時間があったら、下記のフォーマットが見やすいかもしれません！　どちらでも構わないです！

````suggestion
\begin{tcolorbox}[title=リスト1.1 compose.yaml]
  \begin{verbatim}
```

2023-05-07 14:25 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +\begin{tcolorbox}[breakable]
こちらもお時間があったら、下記のフォーマットが見やすいかもしれません！　どちらでも構わないです！

````suggestion
\begin{tcolorbox}[title=dockerfile]
  \begin{verbatim}
```

2023-05-07 14:28 UTC, hihumikan approved these changes
@harutiro 
ビルドは確認できたので、あとは任せます

2023-05-07 23:50 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +```
あっ...

2023-05-08 00:27 UTC, karasuneo commented on content/03-Tech/chap3.tex
> +\includegraphics[width=4cm]{./image/03-Tech/chap3/neo4j_result.png}
10cmに修正しました！

2023-05-08 00:28 UTC, karasuneo commented on content/03-Tech/chap3.tex
> +\includegraphics[width=4cm]{./image/03-Tech/chap3/sample_node.png}
こちらも10cmに修正しました！

2023-05-08 10:40 UTC, harutiro commented
@karasuneo 
混ぜても大丈夫ですか？

2023-05-08 22:26 UTC, hihumikan commented
@karasuneo

2023-05-08 22:36 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +    \begin{verbatim}
ビルドしてないけどこれ消した方がいいかも

2023-05-14 03:27 UTC, happy663 commented on content/03-Tech/chap3.tex
> +csvファイルを読ませるためのシェルスクリプト
全体統一するために「。」をつけたほうがよさそう

2023-05-14 03:27 UTC, happy663 commented on content/03-Tech/chap3.tex
> +Neo4j関連のDockerfile
全体統一するために「。」をつけたほうがよさそう

2023-05-15 07:54 UTC, karasuneo commented on content/03-Tech/chap3.tex
> +Neo4j関連のDockerfile
ありがとうございます！
修正しました！

2023-05-15 07:54 UTC, karasuneo commented on content/03-Tech/chap3.tex
> +csvファイルを読ませるためのシェルスクリプト
ありがとうございます！
修正しました！

2023-05-15 07:56 UTC, karasuneo commented on content/03-Tech/chap3.tex
> +    \begin{verbatim}
ありがとうございます！
修正しました！

2023-05-15 10:06 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +\begin{tcolorbox}[title=dockerfile]
DockerfileDockerfile

2023-05-15 10:06 UTC, hihumikan commented on content/03-Tech/chap3.tex
> +\begin{tcolorbox}[title=dockerfile]
Dockerfile

2023-05-15 10:08 UTC, hihumikan requested changes

2023-05-15 10:08 UTC, hihumikan commented on index.pdf
index.pdfがconflictしているようです..

2023-05-15 15:07 UTC, hihumikan approved these changes

2023-05-15 15:07 UTC, merged