Create imprint
SystemEngineeringTeam/sysken-book-2023 pull request #36
Opened 2023-05-16 15:14 UTC by harutiro

## 概要

- 表紙・裏表紙の変更
- 奥付けの作成
- セクション・目次の調整

## チェックリスト

### Texについての確認リスト
- [x] ビルドが通るか
- [x] 余分な空ページはないか？
- [x] セクションの番号は合っているか？

### 内容についての確認リスト
- [x] 内容に誤字脱字はないか？
- [x] 図と表は正しくラベル付けされているか？
- [x] 引用は正しく行えているか？
- [x] あいまいな文章やねじれている文章になっていないか？
- [x] 段落内・段落同士のつながりは適切か？

## コメント

セクション関係をガラッと変えたので確認を。

2023-05-17 02:45 UTC, hihumikan reviewed
1.2.1 どんな活動をしているの？
stech-> STECH

2023-05-17 02:48 UTC, hihumikan reviewed
>Qiita アドベントカレンダーへの参加もしています。*4

注釈って句読点の後に入れるものだったっけ..(忘れた

2023-05-17 02:49 UTC, hihumikan commented
1.2.2 2021～2022 年度の活動実績
2022 Geekcamp アドバンス 登壇
Geekcamp -> 技育CAMP

2023-05-17 02:51 UTC, hihumikan reviewed
2.4.2 プロジェクト作成からサーバ起動
app ディレクトリは実験段階の機能なので,next.config.js を変更する。
app ディレクトリは実験段階の機能なので、next.config.js を変更する。

2023-05-17 03:04 UTC, hihumikan requested changes

2023-05-17 03:04 UTC, hihumikan commented on content/05-End/atTheEnd.tex
> +そんな中、私がC101の冬コミで技術本というものに出会いました、一つ一つ個人で調べたり研究した情報を、本という形で残すことにとてもいいと思い、今回このような本を執筆しました。
助詞不足？(要議論
```suggestion
そんな中、私がC101の冬コミで技術本というものに出会いました、一つ一つ個人で調べたり研究した情報を、本という形で残すことにとてもいいと思い、今回はこのような本を執筆しました。
```

2023-05-17 03:04 UTC, hihumikan commented on content/05-End/atTheEnd.tex
> +本というものは知識としてずっと蓄えられるものですので、私たちが書いた本が誰かの役にたてればと思い、締めさせてもらいます。
冗長な気がしなくもない(要議論
```suggestion
本は知識としてずっと蓄えられるものですので、私たちが書いた本が誰かの役にたてればと思い、締めさせてもらいます。
```

2023-05-17 03:05 UTC, hihumikan reviewed
2.3.6 実行方法
今回は Vscode の拡張機能である～
Vscode -> VSCode

2023-05-17 03:07 UTC, hihumikan reviewed
2.3.1 はじめに
 DB である Neo4j と Github でも
 Github -> GitHub
 
 他にもこれの表記ゆれありそう

2023-05-17 03:09 UTC, hihumikan commented on content/03-Tech/chap1.tex
> +    \item p.7 『DiscordBot を作ってみよう』suda
改行が入ってないので見づらい気がする

2023-05-17 03:10 UTC, hihumikan reviewed
1.2.2 2021～2022 年度の活動実績
空白が全角なのか半角なのか無いのか表記の揺れがありそう
![image](https://github.com/SystemEngineeringTeam/sysken-book-2023/assets/26848713/3a6be332-9bac-4e50-8659-d56a98b3f602)

2023-05-17 03:12 UTC, hihumikan reviewed
1.2.1 どんな活動をしているの？
Qiita アドベントカレンダー　なのか　Advent Calendar 2022なのか表記の揺れ

2023-05-17 03:12 UTC, hihumikan reviewed
1.2.1 どんな活動をしているの？
大幅な工事を行なっておりごく一部のサービスのみ稼働しています（すみません）
-> 大幅な工事を行なっておりごく一部のサービスのみ稼働しています（すみません）。

2023-05-17 03:16 UTC, hihumikan commented on content/03-Tech/section2.tex
> +\subsubsection{.gitignore}
subsubセクションに変えるとマジで見ずらくなってしまった..どうしよう

2023-05-18 10:04 UTC, harutiro commented on content/03-Tech/section2.tex
> +\subsubsection{.gitignore}
どうしますか？
何か対処があれば教えてください。

2023-05-18 10:13 UTC, hihumikan commented on content/03-Tech/section2.tex
> +\subsubsection{.gitignore}
ここは無視でいいや

2023-05-18 10:13 UTC, hihumikan commented on content/03-Tech/section2.tex
> +\subsubsection{.gitignore}
@harutiro

2023-05-18 12:16 UTC, hihumikan approved these changes
ありがとう!　

2023-05-18 13:18 UTC, merged